#!/bin/bash
# old GIF version
rm -f tmp.gif latest-animation.gif 2>/dev/null
convert -delay 20 -density 150 *.svg -scale 800x tmp.gif
gifsicle -O3 --colors 255 --lossy=30 tmp.gif -o latest-animation.gif && rm -f tmp.gif 2>/dev/null

# new WEBM via PNG version
rm latest-animation.webm 2>/dev/null	# remove old animation 
rm *.png 2>/dev/null			# remove old PNGs
mogrify -format png *.svg		# convert all SVGs to PNG
# generate video
ffmpeg -r 8 -framerate 8 -pattern_type glob -i '*.png' -c:v libvpx-vp9 -pix_fmt yuva420p -vf fps=8 latest-animation.webm
rm *.png 2>/dev/null			# remove old PNGs

